logLevel = "INFO"
InsecureSkipVerify = true
defaultEntryPoints = ["http"]

[api]
  entryPoint = "traefik"
  dashboard = true

[file]

[metrics]
  [metrics.prometheus]
  entryPoint = "traefik"
  buckets = [0.1,0.3,1.2,5.0]

[web]
address = ":8080"

[web.metrics.prometheus]
buckets=[0.1,0.3,1.2,5.0]

[entryPoints]
  [entryPoints.http]
  address = ":80"
 [entryPoints.traefik]
   address=":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "iplabs.de"
watch = true
exposedbydefault = false